InfusionStabiliser update
GTNewHorizons/twilightforest pull request #77
Opened 2024-06-21 07:32 UTC by zhehedream

Backport https://github.com/TeamTwilight/twilightforest/commit/c9d8836e44262f02188aab000f565509f8584621

Now FireflyJar, Trophy & TrophyPedestal will be considered as Infusion Stabiliser 

![2024-06-20_22 59 53](https://github.com/GTNewHorizons/twilightforest/assets/17870449/6987db6c-7f9a-4fbd-b2ea-717df74520a1)

2024-06-26 18:39 UTC, Alastors requested changes
No to firefly jars, they’re too common and there’s already enough lag related to infusion stabilizers anyway

2024-06-26 18:40 UTC, Alastors commented
Trophies are probably fine, they’re just glorified heads anyway

not sure about the trophy pedestal though

2024-06-26 19:02 UTC, Dream-Master commented
drop fireflies if it lag and keep the other items/blocks

2024-06-27 12:37 UTC, Alastors approved these changes

2024-06-27 13:52 UTC, merged

2024-06-27 16:19 UTC, Gordon-Frohman commented
Oh, I was going to do just that in my PR
Guess great minds think alike :smile: