Fix biome IDs over 255 not working for Magic Map and the Stream biome
GTNewHorizons/twilightforest pull request #97
Opened 2024-12-21 21:31 UTC by 48a3efa65c881ef567345b17f3910e06

Note that when auto generating biome ids it still uses the old range of 256 but this shouldn't be a problem because you would have changed all the biome configs anyawy

2024-12-21 21:43 UTC, mitchej123 requested changes

2024-12-21 21:43 UTC, mitchej123 commented on src/main/java/twilightforest/item/ItemTFMagicMap.java
> +                            int[] biomeFrequencies = new int[32768];
This should not be hardcoded and instead should be based on the presence (or lack thereof) of ID extenders.

2025-01-03 21:04 UTC, Dream-Master commented
@48a3efa65c881ef567345b17f3910e06 any update?

2025-01-15 05:43 UTC, serenibyss commented
@mitchej123 Could you re-review this when you get a chance?

2025-01-15 18:27 UTC, mitchej123 approved these changes

2025-01-15 22:09 UTC, merged